//var http = require('https');
//var path = require('path');
var express = require('express');
//var bodyParser = require('body-parser');
var app = express();
//app.use(bodyParser.urlencoded({ extended: true }));
//app.use(bodyParser.json());
//app.use("/public", express.static(__dirname + '/public'));
app.use("/", express.static(__dirname + '/public'));
//app.use("/bower_components", express.static(__dirname + '/bower_components'));
app.listen(process.env.PORT || 3000);
